imp: fix initialize_sudo_support() prototype
Problem: The declared prototype for the static function
initialize_sudo_support() is incorrect in imp.c - it is missing the
function argument. This can cause unexpected behavior and generates
an error in Clang 15:

  imp.c:71:33: error: passing arguments to 'initialize_sudo_support'
    without a prototype is deprecated in all versions of C and is not
    supported in C2x [-Werror,-Wdeprecated-non-prototype]

Fix the prototype.